spring.application.name=springBootTest
spring.profiles.active=dev
# 关闭 devtools 自动覆盖（避免它把 server.port 改成随机端口）
spring.devtools.add-properties=false
#????????
logging.level.root=info
logging.level.com.fengling.springboot=warn
#??????????
logging.file.name=log/xx.log
#?????????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  %level %logger{50}.%M %L:%m%n
#??
logging.pattern.file=logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  %level %logger{50}.%M %L:%m%n